import uuid
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, validator, AliasChoices

class PapanekDimension(str, Enum):
    METHOD = "Method"
    USE = "Use"
    ASSOCIATION = "Association"
    AESTHETICS = "Aesthetics"
    TELESIS = "Telesis"
    NEED = "Need"
    EMERGENT = "Emergent"

class StudentState(str, Enum):
    GROUNDED = "Grounded"
    UNSTABLE = "Unstable"  # Half-life point reached
    COLLAPSED = "Collapsed" # Complete reasoning breakdown
    PAUSED = "Paused"

class InterventionType(str, Enum):
    PAUSE = "pause"
    REDIRECT = "redirect"
    CHALLENGE = "challenge"

class ResponseSource(str, Enum):
    # STUDENT is retained only so transcripts recorded before this change still
    # load. It is no longer assigned: the system cannot observe that an answer was
    # student-written, only that it did or did not derive from the in-app Advocate.
    # Claiming "Student" asserted knowledge it never had, and made the Review Card
    # report "100% student-only" for sessions where nothing had been verified.
    STUDENT = "Student"
    ADVOCATE = "Advocate"
    HYBRID = "Hybrid"
    UNVERIFIED = "Unverified"

class Claim(BaseModel):
    id: str = Field(..., description="Unique claim identifier, e.g., C-01")
    text: str = Field(..., description="The assertable claim extracted from the document")
    is_implicit: bool = Field(..., description="True if the claim is an unstated implicit assumption")
    dimension: PapanekDimension = Field(..., description="Which of Papanek's 6 design dimensions this claim maps to")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Preliminary confidence score based on document justification")
    source_passage: str = Field(..., description="The original passage/paragraph context from the document")
    page: int = Field(..., description="The page number of the source passage")
    probing_questions: List[str] = Field(default_factory=list, description="List of 3 escalating Socratic probing questions")
    vulnerability_rank: int = Field(0, description="Probing priority ranking (lowest confidence in least-discussed dimensions is ranked highest)")
    emergent_theme: Optional[str] = Field(None, description="Dynamically discovered unencoded theme name, if dimension is Emergent")

class EpistemicMap(BaseModel):
    document_name: str = Field(..., description="Name of the parsed PDF/text file")
    claims: List[Claim] = Field(default_factory=list, description="All extracted explicit and implicit claims")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())

    def get_claim(self, claim_id: str) -> Optional[Claim]:
        """Helper method to retrieve a claim by ID."""
        return next((c for c in self.claims if c.id == claim_id), None)

class ProbeTurn(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique turn identifier")
    turn_index: int = Field(..., description="1-indexed counter of conversational turns")
    claim_id: str = Field(..., description="The ID of the Claim being probed")
    question: str = Field(..., description="The Socratic probing question generated by the agent")
    student_response: str = Field(..., description="The student's verbal or written justification")

    # Field-knowledge-independent metrics (individual components)
    coherence_nli: float = Field(default=0.5, ge=0.0, le=1.0, description="Coherence NLI component (logical consistency)")
    coherence_sts: float = Field(default=0.5, ge=0.0, le=1.0, description="Coherence STS component (semantic similarity)")
    grounding_nli: float = Field(default=0.5, ge=0.0, le=1.0, description="Grounding NLI component")
    grounding_sts: float = Field(default=0.5, ge=0.0, le=1.0, description="Grounding STS component")
    variance_nli: float = Field(default=0.0, ge=0.0, le=1.0, description="Variance NLI component")
    variance_sts: float = Field(default=0.0, ge=0.0, le=1.0, description="Variance STS component")

    # Field-knowledge-independent metrics (averaged for backward compatibility)
    coherence_score: float = Field(..., ge=0.0, le=1.0, description="Coherence between probe and response (avg of NLI/STS)")
    grounding_score: float = Field(..., ge=0.0, le=1.0, description="Grounding fact-check score against original claim (avg of NLI/STS)")
    variance_score: float = Field(..., ge=0.0, le=1.0, description="Evaluation variance across simulated temperature runs (avg of NLI/STS)")
    circularity_score: float = Field(..., ge=0.0, le=1.0, description="Circularity and self-referential redundancy score")
    composite_confidence: float = Field(..., ge=0.0, le=1.0, description="Combined confidence score from the classifier")

    # Per-criterion rubric support and document-contradiction trace
    rubric_criterion_scores: Dict[str, float] = Field(default_factory=dict, description="Support score per rubric criterion id")
    contradiction_signal: float = Field(default=0.5, ge=0.0, le=1.0, description="Lowest per-sentence support against the documentation; low values indicate contradiction")
    contradicted_sentence: Optional[str] = Field(None, description="Documentation sentence most relevant to the response, for faculty review")

    # State and routing
    state: StudentState = Field(..., description="Evaluated state of the student's reasoning")
    # Longitudinal instability trace. Defaulted so transcripts recorded before
    # escalation existed still load; a False/0 pair means "recorded pre-feature or
    # never escalated", which is why raw_state is kept alongside the final state.
    consecutive_unstable_turns: int = Field(0, ge=0, description="Consecutive unstable turns on this claim, counting this turn")
    escalated_from_unstable: bool = Field(False, description="True if COLLAPSED was reached by sustained instability rather than by crossing the per-turn composite threshold")
    raw_state: Optional[StudentState] = Field(None, description="Per-turn threshold state before any sustained-instability escalation was applied")
    reconstruction_dimension: Optional[PapanekDimension] = Field(None, description="Dimension used for routing alternative-angle recovery upon collapse")
    intervention_type: Optional[InterventionType] = Field(None, description="The type of student intervention invoked, if any")
    weight_version: str = Field("A", description="Version of classifier weights used for evaluation ('A' or 'B')")
    # Defaults to v1-legacy so transcripts recorded before the reweighting identify
    # themselves; without this, old and new composites would be indistinguishable.
    composite_weights_version: str = Field("v1-legacy", description="Which composite weight set produced composite_confidence")
    # Live scores, kept when the end-of-session audit rescores the turn. Routing
    # during the session reacted to these, so the path the viva took is only
    # explicable from them; the audited values sit in composite_confidence/state.
    provisional_composite: Optional[float] = Field(None, ge=0.0, le=1.0, description="Composite as scored live during the session, before the end-of-session audit")
    provisional_state: Optional[StudentState] = Field(None, description="State as scored live during the session, before the end-of-session audit")
    emergent_theme: Optional[str] = Field(None, description="The emergent theme name if active claim dimension is Emergent")
    response_source: ResponseSource = Field(ResponseSource.UNVERIFIED, description="Provenance relative to the in-app Advocate: ADVOCATE (submitted near-verbatim), HYBRID (edited), UNVERIFIED (no Advocate draft was generated, so provenance is unobserved)")
    # The Advocate draft and how far the submission diverged from it. Previously
    # the draft was discarded the moment response_source was decided, so the
    # "intervention log" the design docs call "the richest data source in the
    # session" was never actually recorded - only a three-way bucket survived.
    # Both are None when no draft was generated (nothing to compare against).
    advocate_draft: Optional[str] = Field(None, description="Raw Advocate-generated suggestion text offered for this turn, if one was generated")
    advocate_similarity: Optional[float] = Field(None, ge=0.0, le=1.0, description="difflib similarity ratio between the submitted response and the Advocate draft; 1.0 = submitted verbatim, 0.0 = unrecognisable from the draft")

class FacultyLabel(BaseModel):
    turn_id: str = Field(..., description="The unique turn ID being labelled")
    labeller_id: str = Field(..., description="ID of the faculty labeller")
    agrees_with_system: bool = Field(..., description="True if labeller agrees with the system's state assessment")
    corrected_state: Optional[StudentState] = Field(None, description="Corrected StudentState if labeller disagrees")
    note: Optional[str] = Field(None, description="Qualitative feedback or note from the labeller")
    labelled_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp of when labelling occurred")

class FacultyRubricLabel(BaseModel):
    claim_id: str = Field(..., description="The unique claim ID being evaluated")
    labeller_id: str = Field(..., description="ID of the faculty labeller")
    labelled_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class ReviewCard(BaseModel):
    composite_confidence: float = Field(..., ge=0.0, le=1.0, description="The primary structural composite confidence score used in the session")
    version_a_composite: Optional[float] = Field(None, ge=0.0, le=1.0, description="Version A (Heuristics) composite confidence score")
    version_b_composite: Optional[float] = Field(None, ge=0.0, le=1.0, description="Version B (ML model) composite confidence score")
    rubric_scores: List[RubricScore] = Field(default_factory=list, description="Qualitative rubric scores")
    session_notes: Optional[str] = Field(None, description="Qualitative feedback comments")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class EvaluatorRating(BaseModel):
    session_id: str = Field(..., description="ID of the SessionTranscript rated")
    evaluator_id: str = Field(..., description="ID of the independent evaluator")
    judgement: str = Field(..., description="Evaluator's judgement (e.g., 'Collapsed', 'Grounded', 'Unstable')")
    rating_score: float = Field(..., ge=0.0, le=1.0, description="Score given by the independent evaluator")
    notes: Optional[str] = Field(None, description="Qualitative feedback notes")
    submitted_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")
    blind: bool = Field(True, description="True if the evaluator was blind to system scores")

class ChallengeRecord(BaseModel):
    turn_id: str = Field(..., description="The unique turn ID being disputed")
    turn_index: int = Field(..., description="1-indexed turn number being disputed")
    disputed_state: StudentState = Field(..., description="The reasoning state the student is disputing")
    system_explanation: str = Field(..., description="The system's epistemic justification, exactly as shown to the student at the time of the challenge")
    student_justification: Optional[str] = Field(None, description="The student's reasoning for disputing the score, if they chose to provide one")
    challenged_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class ExperimentProfile(BaseModel):
    profile_name: str = Field(..., description="The name of the temperature profile (e.g., 'Baseline', 'High Creativity')")
    assessor_temp: float = Field(..., description="Temperature for the Socratic Assessor")
    evaluator_temp: float = Field(..., description="Temperature for the grading Evaluator")
    advocate_temp: float = Field(..., description="Temperature for the Advocate Helper")

class FacultyExperimentRating(BaseModel):
    turn_index: int = Field(..., description="The index of the turn being rated")
    assessor_hallucination: bool = Field(..., description="Did the Assessor hallucinate?")
    assessor_repetition: bool = Field(..., description="Did the Assessor repeat itself?")
    evaluator_variance_accurate: bool = Field(..., description="Did the Evaluator's Variance score correctly reflect the ambiguity?")
    advocate_novel: bool = Field(..., description="Was the Advocate pivot novel?")
    advocate_relevant: bool = Field(..., description="Was the Advocate pivot relevant?")
    expert_alignment: bool = Field(False, description="Did the AI response align with expert pedagogical expectations?")
    ground_truth_score: float = Field(..., ge=0.0, le=1.0, description="Faculty's Ground Truth grade (0.0 to 1.0) for the student's raw answer")
    faculty_id: str = Field(..., description="ID of the faculty rater")
    rated_at: str = Field(default_factory=lambda: datetime.now().isoformat())

class SessionTranscript(BaseModel):
    session_id: str = Field(..., description="Unique session UUID")
    student_name: str = Field(..., description="Name of the student being examined")
    document_name: str = Field(..., description="Name of the student's submitted document")
    epistemic_map: EpistemicMap = Field(..., description="The extracted epistemic map used as the session foundation")
    turns: List[ProbeTurn] = Field(default_factory=list, description="Chronological log of probing turns")
    started_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None
    notes: Optional[str] = Field(None, description="Examiner comments or longitudinal assessment summary")
    
    # Extended fields
    weight_version: str = Field("A", description="Classifier weights version used in the session")
    assignment_brief: Optional[str] = Field(None, description="Optional assignment brief supplied at session setup, used as extra context when the auditor scores evidence")
    final_audit: Optional[Dict[str, Any]] = Field(None, description="End-of-session auditor pass: portfolio scores, mean, variance and rationales")
    # Cached output of consistency.analyse_document (serialised via
    # consistency.to_serialisable). None until a faculty member runs the check
    # from the Feedback Dashboard - it is exhaustive over every claim pair in the
    # document (a 91-claim map took ~42s), so it is computed on demand and cached
    # here rather than run automatically on every session or every dashboard load.
    document_integrity: Optional[Dict[str, Any]] = Field(None, description="Cached document-level foundedness and cross-claim contradiction report, computed on demand from the Feedback Dashboard")
    faculty_labels: List[FacultyLabel] = Field(default_factory=list, description="Labels assigned by faculty members")
    faculty_rubric_labels: List[FacultyRubricLabel] = Field(default_factory=list, description="Qualitative rubric labels assigned by faculty")
    evaluator_ratings: List[EvaluatorRating] = Field(default_factory=list, description="Independent blind evaluations")
    review_card: Optional[ReviewCard] = Field(None, description="Faculty review card dashboard data")
    telemetry_export: Optional[Dict[str, Any]] = Field(None, description="Exportable telemetry logs for all three agents (Advocate, Assessor, Evaluator)")
    experiment_profile: Optional[ExperimentProfile] = Field(None, description="The randomized LLM temperature profile assigned to this session")
    experiment_ratings: List[FacultyExperimentRating] = Field(default_factory=list, description="Double-blind faculty ratings for the temperature experiment")
    challenges: List[ChallengeRecord] = Field(default_factory=list, description="Student-initiated disputes of scoring decisions")
