import uuid
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field, validator, AliasChoices

class PapanekDimension(str, Enum):
    METHOD = "Method"
    USE = "Use"
    ASSOCIATION = "Association"
    AESTHETICS = "Aesthetics"
    TELESIS = "Telesis"
    NEED = "Need"
    EMERGENT = "Emergent"

class StudentState(str, Enum):
    GROUNDED = "Grounded"
    UNSTABLE = "Unstable"  # Half-life point reached
    COLLAPSED = "Collapsed" # Complete reasoning breakdown
    PAUSED = "Paused"

class InterventionType(str, Enum):
    PAUSE = "pause"
    REDIRECT = "redirect"
    CHALLENGE = "challenge"

class ResponseSource(str, Enum):
    STUDENT = "Student"
    ADVOCATE = "Advocate"
    HYBRID = "Hybrid"

class Claim(BaseModel):
    id: str = Field(..., description="Unique claim identifier, e.g., C-01")
    text: str = Field(..., description="The assertable claim extracted from the document")
    is_implicit: bool = Field(..., description="True if the claim is an unstated implicit assumption")
    dimension: PapanekDimension = Field(..., description="Which of Papanek's 6 design dimensions this claim maps to")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Preliminary confidence score based on document justification")
    source_passage: str = Field(..., description="The original passage/paragraph context from the document")
    page: int = Field(..., description="The page number of the source passage")
    probing_questions: List[str] = Field(default_factory=list, description="List of 3 escalating Socratic probing questions")
    vulnerability_rank: int = Field(0, description="Probing priority ranking (lowest confidence in least-discussed dimensions is ranked highest)")
    emergent_theme: Optional[str] = Field(None, description="Dynamically discovered unencoded theme name, if dimension is Emergent")

class EpistemicMap(BaseModel):
    document_name: str = Field(..., description="Name of the parsed PDF/text file")
    claims: List[Claim] = Field(default_factory=list, description="All extracted explicit and implicit claims")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())

    def get_claim(self, claim_id: str) -> Optional[Claim]:
        """Helper method to retrieve a claim by ID."""
        return next((c for c in self.claims if c.id == claim_id), None)

class ProbeTurn(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique turn identifier")
    turn_index: int = Field(..., description="1-indexed counter of conversational turns")
    claim_id: str = Field(..., description="The ID of the Claim being probed")
    question: str = Field(..., description="The Socratic probing question generated by the agent")
    student_response: str = Field(..., description="The student's verbal or written justification")

    # Field-knowledge-independent metrics
    coherence_score: float = Field(..., ge=0.0, le=1.0, description="Coherence between probe and response")
    grounding_score: float = Field(..., ge=0.0, le=1.0, description="Grounding fact-check score against original claim")
    variance_score: float = Field(..., ge=0.0, le=1.0, description="Evaluation variance across simulated temperature runs")
    circularity_score: float = Field(..., ge=0.0, le=1.0, description="Circularity and self-referential redundancy score")
    composite_confidence: float = Field(..., ge=0.0, le=1.0, description="Combined confidence score from the classifier")

    # State and routing
    state: StudentState = Field(..., description="Evaluated state of the student's reasoning")
    reconstruction_dimension: Optional[PapanekDimension] = Field(None, description="Dimension used for routing alternative-angle recovery upon collapse")
    intervention_type: Optional[InterventionType] = Field(None, description="The type of student intervention invoked, if any")
    weight_version: str = Field("A", description="Version of classifier weights used for evaluation ('A' or 'B')")
    emergent_theme: Optional[str] = Field(None, description="The emergent theme name if active claim dimension is Emergent")
    response_source: ResponseSource = Field(ResponseSource.STUDENT, description="Whether response was student-written, advocate-suggested, or hybrid")
    rubric_scores: List['RubricScore'] = Field(default_factory=list, description="Per-turn qualitative rubric scores (empathy, internalisation, confidence)")

class FacultyLabel(BaseModel):
    turn_id: str = Field(..., description="The unique turn ID being labelled")
    labeller_id: str = Field(..., description="ID of the faculty labeller")
    agrees_with_system: bool = Field(..., description="True if labeller agrees with the system's state assessment")
    corrected_state: Optional[StudentState] = Field(None, description="Corrected StudentState if labeller disagrees")
    note: Optional[str] = Field(None, description="Qualitative feedback or note from the labeller")
    labelled_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp of when labelling occurred")

class FacultyRubricLabel(BaseModel):
    claim_id: str = Field(..., description="The unique claim ID being evaluated")
    labeller_id: str = Field(..., description="ID of the faculty labeller")
    internalisation_anchor: str = Field(..., description="Faculty label for Internalisation (Low/Mid/High)")
    originality_anchor: str = Field(..., description="Faculty label for Originality (Low/Mid/High)")
    confidence_anchor: str = Field(..., description="Faculty label for Confidence (Low/Mid/High)")
    empathy_anchor: str = Field(..., description="Faculty label for Empathy (Low/Mid/High)")
    labelled_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class RubricConstruct(str, Enum):
    INTERNALISATION = "Internalisation"
    ORIGINALITY = "Originality"
    CONFIDENCE_CONVICTION = "Confidence_Conviction"
    EMPATHY = "Empathy"

class RubricScore(BaseModel):
    claim_id: str = Field(..., description="The ID of the Claim being scored")
    rubric_construct: RubricConstruct = Field(..., validation_alias=AliasChoices('construct', 'rubric_construct'), description="The qualitative rubric construct")
    bucket: str = Field(..., description="The bucket category ('A', 'B', or 'C')")
    score: float = Field(..., ge=0.0, le=1.0, description="Score value between 0.0 and 1.0")
    anchor_level: str = Field(..., description="Qualitative level descriptive label (e.g. 'Low', 'Mid', 'High')")
    source: str = Field(..., description="Scoring source (e.g., 'auto', 'human', 'auto-draft')")

class ReviewCard(BaseModel):
    composite_confidence: float = Field(..., ge=0.0, le=1.0, description="The primary structural composite confidence score used in the session")
    version_a_composite: Optional[float] = Field(None, ge=0.0, le=1.0, description="Version A (Heuristics) composite confidence score")
    version_b_composite: Optional[float] = Field(None, ge=0.0, le=1.0, description="Version B (ML model) composite confidence score")
    rubric_scores: List[RubricScore] = Field(default_factory=list, description="Qualitative rubric scores")
    session_notes: Optional[str] = Field(None, description="Qualitative feedback comments")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class EvaluatorRating(BaseModel):
    session_id: str = Field(..., description="ID of the SessionTranscript rated")
    evaluator_id: str = Field(..., description="ID of the independent evaluator")
    judgement: str = Field(..., description="Evaluator's judgement (e.g., 'Collapsed', 'Grounded', 'Unstable')")
    rating_score: float = Field(..., ge=0.0, le=1.0, description="Score given by the independent evaluator")
    notes: Optional[str] = Field(None, description="Qualitative feedback notes")
    submitted_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")
    blind: bool = Field(True, description="True if the evaluator was blind to system scores")

class ChallengeRecord(BaseModel):
    turn_id: str = Field(..., description="The unique turn ID being disputed")
    turn_index: int = Field(..., description="1-indexed turn number being disputed")
    disputed_state: StudentState = Field(..., description="The reasoning state the student is disputing")
    system_explanation: str = Field(..., description="The system's epistemic justification, exactly as shown to the student at the time of the challenge")
    student_justification: Optional[str] = Field(None, description="The student's reasoning for disputing the score, if they chose to provide one")
    challenged_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO timestamp")

class ExperimentProfile(BaseModel):
    profile_name: str = Field(..., description="The name of the temperature profile (e.g., 'Baseline', 'High Creativity')")
    assessor_temp: float = Field(..., description="Temperature for the Socratic Assessor")
    evaluator_temp: float = Field(..., description="Temperature for the grading Evaluator")
    advocate_temp: float = Field(..., description="Temperature for the Advocate Helper")

class FacultyExperimentRating(BaseModel):
    turn_index: int = Field(..., description="The index of the turn being rated")
    assessor_hallucination: bool = Field(..., description="Did the Assessor hallucinate?")
    assessor_repetition: bool = Field(..., description="Did the Assessor repeat itself?")
    evaluator_variance_accurate: bool = Field(..., description="Did the Evaluator's Variance score correctly reflect the ambiguity?")
    advocate_novel: bool = Field(..., description="Was the Advocate pivot novel?")
    advocate_relevant: bool = Field(..., description="Was the Advocate pivot relevant?")
    ground_truth_score: float = Field(..., ge=0.0, le=1.0, description="Faculty's Ground Truth grade (0.0 to 1.0) for the student's raw answer")
    faculty_id: str = Field(..., description="ID of the faculty rater")
    rated_at: str = Field(default_factory=lambda: datetime.now().isoformat())

class SessionTranscript(BaseModel):
    session_id: str = Field(..., description="Unique session UUID")
    student_name: str = Field(..., description="Name of the student being examined")
    document_name: str = Field(..., description="Name of the student's submitted document")
    epistemic_map: EpistemicMap = Field(..., description="The extracted epistemic map used as the session foundation")
    turns: List[ProbeTurn] = Field(default_factory=list, description="Chronological log of probing turns")
    started_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None
    notes: Optional[str] = Field(None, description="Examiner comments or longitudinal assessment summary")
    
    # Extended fields
    weight_version: str = Field("A", description="Classifier weights version used in the session")
    faculty_labels: List[FacultyLabel] = Field(default_factory=list, description="Labels assigned by faculty members")
    faculty_rubric_labels: List[FacultyRubricLabel] = Field(default_factory=list, description="Qualitative rubric labels assigned by faculty")
    evaluator_ratings: List[EvaluatorRating] = Field(default_factory=list, description="Independent blind evaluations")
    review_card: Optional[ReviewCard] = Field(None, description="Faculty review card dashboard data")
    telemetry_export: Optional[Dict[str, Any]] = Field(None, description="Exportable telemetry logs for all three agents (Advocate, Assessor, Evaluator)")
    experiment_profile: Optional[ExperimentProfile] = Field(None, description="The randomized LLM temperature profile assigned to this session")
    experiment_ratings: List[FacultyExperimentRating] = Field(default_factory=list, description="Double-blind faculty ratings for the temperature experiment")
    challenges: List[ChallengeRecord] = Field(default_factory=list, description="Student-initiated disputes of scoring decisions")
